language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    recipients:
      - arne@arnebrasseur.net
    on_success: never
    on_failure: change
script: bundle exec rake ci:metrics